### ISSUE TITLE
seafile-applet cores dump instantly II: No such slot AccountManager::reloginAccount

### ISSUE THREAD

**Issue by kforner** [haiwen/seafile-user-manual#46]
``` 
pkill -f seaf
seafile-applet
Segmentation fault (core dumped)
```

If I look at the log `~/.ccnet/logs/applet.log`, I see:
```
[10/10/2018 11:35:43 AM]QObject::connect: No such slot AccountManager::reloginAccount(const Account &)
[10/10/2018 11:35:43 AM]starting ccnet:  ("-c", "/home/karl/.ccnet")
```
config:
```
$ dpkg -l | grep seaf
ii  libseafile0                                       6.1.8-1240~ubuntu16.04.1                     amd64        Shared libraries for Seafile
ii  seafile-cli                                       6.1.8-1240~ubuntu16.04.1                     amd64        Seafile command line interface.
ii  seafile-daemon                                    6.1.8-1240~ubuntu16.04.1                     amd64        Seafile daemon
ii  seafile-gui                                       6.1.8-1431~ubuntu16.04.1                     amd64        Seafile desktop client.

Ubuntu 16.04.5 LTS

Linux 4.15.0-36-generic #39~16.04.1-Ubuntu SMP
```

**Comment by kforner** [comment]
I tried compiling the application:

git clone https://github.com/haiwen/seafile-client.git
cd seafile-client/
cmake -DCMAKE_BUILD_TYPE=Debug .
make
```
gdb ./seafile-applet
(gdb) run
Starting program: /home/karl/Downloads/seafile-client/seafile-applet 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffea7ef700 (LWP 25480)]
[New Thread 0x7fffdfc92700 (LWP 25482)]
[New Thread 0x7fffdf491700 (LWP 25483)]
[New Thread 0x7fffdec90700 (LWP 25484)]
[New Thread 0x7fffde48f700 (LWP 25485)]
lang = English, translation = (null), locale.name() = en_US

Thread 1 "seafile-applet" received signal SIGSEGV, Segmentation fault.
0x00007ffff72cd0b3 in searpc_client_transport_send () from /usr/lib/libsearpc.so.1
(gdb) bt
#0  0x00007ffff72cd0b3 in searpc_client_transport_send () from /usr/lib/libsearpc.so.1
#1  0x00007ffff72cdb65 in searpc_client_call.objlist () from /usr/lib/libsearpc.so.1
#2  0x000000000057f358 in SeafileRpcClient::getSyncErrors (this=0xc49570, errors=0x7fffffffc670, offset=0, limit=1) at /home/karl/Downloads/seafile-client/src/rpc/rpc-client.cpp:986
#3  0x00000000005b0d2d in SeafileTrayIcon::prepareContextMenu (this=0xd53000) at /home/karl/Downloads/seafile-client/src/ui/tray-icon.cpp:237
#4  0x000000000066c820 in SeafileTrayIcon::qt_static_metacall (_o=0xd53000, _c=QMetaObject::InvokeMetaMethod, _id=5, _a=0x7fffffffc7d0)
    at /home/karl/Downloads/seafile-client/src/ui/moc_tray-icon.cpp:139
#5  0x00007ffff5aacd2a in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00007ffff656fb5d in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#7  0x00007ffff5aacd2a in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#8  0x00007fffe9574dd3 in ?? () from /usr/lib/x86_64-linux-gnu/qt5/plugins/platformthemes/libappmenu-qt5.so
#9  0x00007fffe9574d2e in ?? () from /usr/lib/x86_64-linux-gnu/qt5/plugins/platformthemes/libappmenu-qt5.so
#10 0x00007fffe9574be1 in ?? () from /usr/lib/x86_64-linux-gnu/qt5/plugins/platformthemes/libappmenu-qt5.so
#11 0x00007ffff5aacbaf in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#12 0x00007ffff656fb5d in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#13 0x00007ffff5a8984a in QMetaMethod::invoke(QObject*, Qt::ConnectionType, QGenericReturnArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument) const () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#14 0x00007ffff5a8ef0d in QMetaObject::invokeMethod(QObject*, char const*, Qt::ConnectionType, QGenericReturnArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#15 0x00007fffe93455c1 in ?? () from /usr/lib/x86_64-linux-gnu/libdbusmenu-qt5.so.2
#16 0x00007fffe934743b in ?? () from /usr/lib/x86_64-linux-gnu/libdbusmenu-qt5.so.2
#17 0x00007fffe93478c8 in ?? () from /usr/lib/x86_64-linux-gnu/libdbusmenu-qt5.so.2
#18 0x00007ffff6236913 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5
#19 0x00007ffff623a5ba in ?? () from /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5
#20 0x00007ffff623af0b in ?? () from /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5
#21 0x00007ffff623c26e in ?? () from /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5
#22 0x00007ffff5aadc01 in QObject::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#23 0x00007ffff63ef05c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#24 0x00007ffff63f4516 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#25 0x00007ffff5a7e38b in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#26 0x00007ffff5a80786 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#27 0x00007ffff5ad43c3 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#28 0x00007ffff6daf197 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#29 0x00007ffff6daf3f0 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#30 0x00007ffff6daf49c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#31 0x00007ffff5ad47cf in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#32 0x00007ffff5a7bb4a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#33 0x00007ffff5a83bec in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#34 0x0000000000523cda in main (argc=1, argv=0x7fffffffdea8) at /home/karl/Downloads/seafile-client/src/main.cpp:225
```

**Comment by killing** [comment]
Have you tried to upgrade to the latest version? And which package repository do you use?

By the way, you'd better ask client related questions on https://github.com/haiwen/seafile-client

**Comment by kforner** [comment]
Hi @killing 

I used the latest version for the ubuntu package repository (as  indicated in my post above 6.1.8-1240~ubuntu16.04.1) and also compiled the latest master from the github repository. 
Is-it possible to move this issue to the seafile-client, or should I recreate it ?

Thanks for your help.

**Comment by kforner** [comment]
Hi @killing 

I used the latest version for the ubuntu package repository (as  indicated in my post above 6.1.8-1240~ubuntu16.04.1) and also compiled the latest master from the github repository. 
Is-it possible to move this issue to the seafile-client, or should I recreate it ?

Thanks for your help.
